AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack sns mscli

Parameters:
  BusPeticionesSflAfvSNSTopicArn:
    Type: String
  ClienteSQSArn:
    Type: String

Resources:
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref BusPeticionesSflAfvSNSTopicArn
      FilterPolicy: { "ID_MICROSERVICIO": [{ "numeric": ["=", 3] }] }
      Endpoint: !Ref ClienteSQSArn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Ref AWS::Region
