AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack lambdas ms distribucion geografica

Globals:
  Function:
    MemorySize: 128
    Tracing: PassThrough
    Timeout: 600
    Runtime: nodejs16.x
    EphemeralStorage:
      Size: 512
    Architectures:
      - "x86_64"
    # VpcConfig:
    #   SubnetIds:
    #     - !Ref SubnetId1
    #   SecurityGroupIds:
    #     - !Ref SecurityGroupIds

Parameters:
  LayerMySQL:
    Type: String
  LayerSecretManager:
    Type: String
  LayerDMFormatter:
    Type: String
  LayerSendEvent:
    Type: String
  LayerAxiosGraphql:
    Type: String

  SecurityGroupIds:
    Type: String
  SubnetId1:
    Type: String

  SecretARNBeval:
    Type: String
  SecretArnFebeca:
    Type: String
  SecretARNSillaca:
    Type: String

  ApiGatewayAPIDmDistGeo:
    Type: String
  StageAPIDmDistGeo:
    Type: String

  RoleLambdaGlobalSflAfvArn:
    Type: String

Resources:
  PullSQSDistGeoLambda: #LambdaFunction5
    Type: AWS::Serverless::Function
    Properties:
      Description: SFL-AFV | Microservicio Division Geografica | Pull de cola SQS
      FunctionName: mave-msdgeo-lbda-pullSQS
      Handler: index.handler
      CodeUri: ../../src/lambdas/msdgeo/mave-msdgeo-lbda-pullSQS
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerSendEvent

  ETLAddDistGeoLambda: #LambdaFunction2:
    Type: AWS::Serverless::Function
    Properties:
      Description: SFL-AFV | Microservicio Division Geografica | ETL Add
      Environment:
        Variables:
          API_DGEO_V1:
            Fn::Sub: https://${ApiGatewayAPIDmDistGeo}.execute-api.${AWS::Region}.amazonaws.com/${StageAPIDmDistGeo}/
      FunctionName: mave-msdgeo-lbda-etl-Add
      ReservedConcurrentExecutions: 1
      Handler: index.handler
      CodeUri: ../../src/lambdas/msdgeo/mave-msdgeo-lbda-etl-Add
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerAxiosGraphql
        - !Ref LayerSendEvent

  ETLUpdateDistGeoLambda: #LambdaFunction
    Type: AWS::Serverless::Function
    Properties:
      Description: SFL-AFV | Microservicio Division Geografica | ETL Update
      Environment:
        Variables:
          API_DGEO_V1:
            Fn::Sub: https://${ApiGatewayAPIDmDistGeo}.execute-api.${AWS::Region}.amazonaws.com/${StageAPIDmDistGeo}/
      FunctionName: mave-msdgeo-lbda-etl-Update
      ReservedConcurrentExecutions: 1
      Handler: index.handler
      CodeUri: ../../src/lambdas/msdgeo/mave-msdgeo-lbda-etl-Update
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerAxiosGraphql
        - !Ref LayerSendEvent

  DMCiudadesDistGeoLambda: #LambdaFunction6
    Type: AWS::Serverless::Function
    Properties:
      Description:
        SFL-AFV | Microservicio Division Geografica | Procesamiento de
        Datos | cyc_ciudad
      Environment:
        Variables:
          SECRET_ARN_BEVAL: !Ref SecretARNBeval
          SECRET_ARN_FEBECA: !Ref SecretArnFebeca
          SECRET_ARN_SILLACA: !Ref SecretARNSillaca
          REGION: !Ref AWS::Region
          TABLE: cyc_ciudad
      FunctionName: mave-msdgeo-lbda-cyc_ciudad
      Handler: index.handler
      CodeUri: ../../src/lambdas/msdgeo/mave-msdgeo-lbda-cyc_ciudad
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerMySQL
        - !Ref LayerSecretManager
        - !Ref LayerDMFormatter

  DmEstadosDistGeoLambda: #LambdaFunction3
    Type: AWS::Serverless::Function
    Properties:
      Description:
        SFL-AFV | Microservicio Division Geografica | Procesamiento de
        Datos | cyc_estados
      Environment:
        Variables:
          SECRET_ARN_BEVAL: !Ref SecretARNBeval
          SECRET_ARN_FEBECA: !Ref SecretArnFebeca
          SECRET_ARN_SILLACA: !Ref SecretARNSillaca
          REGION: !Ref AWS::Region
          TABLE: cyc_estados
      FunctionName: mave-msdgeo-lbda-cyc_estados
      Handler: index.handler
      CodeUri: ../../src/lambdas/msdgeo/mave-msdgeo-lbda-cyc_estados
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerMySQL
        - !Ref LayerSecretManager
        - !Ref LayerDMFormatter

  DMPaisesDistGeoLambda: #LambdaFunction4
    Type: AWS::Serverless::Function
    Properties:
      Description:
        SFL-AFV | Microservicio Division Geografica | Procesamiento de
        Datos | cyc_pais
      Environment:
        Variables:
          SECRET_ARN_BEVAL: !Ref SecretARNBeval
          SECRET_ARN_FEBECA: !Ref SecretArnFebeca
          SECRET_ARN_SILLACA: !Ref SecretARNSillaca
          REGION: !Ref AWS::Region
          TABLE: cyc_pais
      FunctionName: mave-msdgeo-lbda-cyc_pais
      Handler: index.handler
      CodeUri: ../../src/lambdas/msdgeo/mave-msdgeo-lbda-cyc_pais
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerMySQL
        - !Ref LayerSecretManager
        - !Ref LayerDMFormatter

Outputs:
  ETLAddDistGeoLambdaArn:
    Value: !GetAtt ETLAddDistGeoLambda.Arn
  ETLUpdateDistGeoLambdaArn:
    Value: !GetAtt ETLUpdateDistGeoLambda.Arn

  DMCiudadesDistGeoLambdaArn:
    Value: !GetAtt DMCiudadesDistGeoLambda.Arn
  DmEstadosDistGeoLambdaArn:
    Value: !GetAtt DmEstadosDistGeoLambda.Arn
  DMPaisesDistGeoLambdaArn:
    Value: !GetAtt DMPaisesDistGeoLambda.Arn

  PullSQSDistGeoLambdaArn:
    Value: !GetAtt PullSQSDistGeoLambda.Arn
