AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack Lambda permission and triggers msanexos

Parameters:
  DMAnexosLambdaArn:
    Type: String
  BussAnexosLambdaArn: 
    Type: String
  ApiGatewayAPIAnexos:
    Type: String
  AnexosSQSArn:
    Type: String

Resources:
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref DMAnexosLambdaArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIAnexos}/*/POST/anexos"

  LambdaPermission2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref DMAnexosLambdaArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIAnexos}/*/POST/anexosdetalle"

  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Ref AnexosSQSArn
      FunctionName: !Ref BussAnexosLambdaArn
      MaximumBatchingWindowInSeconds: 0
