AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack sns msanex

Parameters:
  BusPeticionesAFVSoftlandSnsArn:
    Type: String
  BusPeticionesXRTAFVSnsArn:
    Type: String
  AnexosSQSArn:
    Type: String

Resources:
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref BusPeticionesAFVSoftlandSnsArn
      FilterPolicy: '{"ID_MICROSERVICIO":[{"numeric":["=",21]}]}'
      Endpoint: !Ref AnexosSQSArn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Ref AWS::Region
  SNSSubscription2:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref BusPeticionesXRTAFVSnsArn
      FilterPolicy: '{"ID_MICROSERVICIO":[{"numeric":["=",21]}]}'
      Endpoint: !Ref AnexosSQSArn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Ref AWS::Region

