AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack SQS ms bancos/cuentas

Parameters:
  BusPeticionesSflAfvSNSTopicArn:
    Type: String

Resources:
  BancosCuentasSQS: #BancosCuentasSQS
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: false
      DelaySeconds: 0
      FifoQueue: true
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 3
      VisibilityTimeout: 30
      QueueName: mave-msban-sqs-BancosCuentas.fifo

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - SQS:*
            Effect: Allow
            Resource: !GetAtt BancosCuentasSQS.Arn
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
          - Action:
              - SQS:SendMessage
            Effect: Allow
            Resource: !GetAtt BancosCuentasSQS.Arn
            Principal:
              AWS:
                - "*"
            Condition:
              ArnLike:
                aws:SourceArn: !Ref BusPeticionesSflAfvSNSTopicArn

      Queues:
        - !Ref BancosCuentasSQS

Outputs:
  BancosCuentasSQSArn:
    Value: !GetAtt BancosCuentasSQS.Arn
