AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack sns msped

Parameters:
  BusPeticionesAfvSflSNSTopicArn:
    Type: String
  PedidosSQSArn:
    Type: String

Resources:
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref BusPeticionesAfvSflSNSTopicArn
      FilterPolicy: { "ID_MICROSERVICIO": [{ "numeric": ["=", 22] }] }
      Endpoint: !Ref PedidosSQSArn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Ref AWS::Region
