Parameters:
  afvBevalDbHost:
    NoEcho: true
    Type: String
  afvBevalDbPort:
    NoEcho: true
    Type: Number
  afvBevalDbUser:
    NoEcho: true
    Type: String
  afvBevalDbPassword:
    NoEcho: true
    Type: String
  afvBevalDbSchema:
    NoEcho: true
    Type: String

  afvFebecaDbHost:
    NoEcho: true
    Type: String
  afvFebecaDbPort:
    NoEcho: true
    Type: Number
  afvFebecaDbUser:
    NoEcho: true
    Type: String
  afvFebecaDbPassword:
    NoEcho: true
    Type: String
  afvFebecaDbSchema:
    NoEcho: true
    Type: String

  afvSillacaDbHost:
    NoEcho: true
    Type: String
  afvSillacaDbPort:
    NoEcho: true
    Type: Number
  afvSillacaDbUser:
    NoEcho: true
    Type: String
  afvSillacaDbPassword:
    NoEcho: true
    Type: String
  afvSillacaDbSchema:
    NoEcho: true
    Type: String

Resources:
  secretManagerDataBaseAfvBeval:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "interfaz de conciliaciones. Datos de conexión con la base de datos de AFV-beval"
      Name: secret-afv-beval-data-base-interface-afv-sfl
      SecretString: !Sub '{"host":"${afvBevalDbHost}", "port":"${afvBevalDbPort}","username":"${afvBevalDbUser}","password":"${afvBevalDbPassword}","schema":"${afvBevalDbSchema}"}'

  secretManagerDataBaseAfvFebeca:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "interfaz de conciliaciones. Datos de conexión con la base de datos de AFV-febeca"
      Name: secret-afv-febeca-data-base-interface-afv-sfl
      SecretString: !Sub '{"host":"${afvFebecaDbHost}", "port":"${afvFebecaDbPort}","username":"${afvFebecaDbUser}","password":"${afvFebecaDbPassword}","schema":"${afvFebecaDbSchema}"}'

  secretManagerDataBaseAfvSillaca:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "interfaz de conciliaciones. Datos de conexión con la base de datos de AFV-sillaca"
      Name: secret-afv-sillaca-data-base-interface-afv-sfl
      SecretString: !Sub '{"host":"${afvSillacaDbHost}", "port":"${afvSillacaDbPort}","username":"${afvSillacaDbUser}","password":"${afvSillacaDbPassword}","schema":"${afvSillacaDbSchema}"}'

Outputs:
  SecretARNBeval:
    Description: "Arn del secret manager de la base de datos AFV-Beval"
    Value: !Ref secretManagerDataBaseAfvBeval

  SecretArnFebeca:
    Description: "Arn del secret manager de la base de datos AFV-Febeca"
    Value: !Ref secretManagerDataBaseAfvFebeca

  SecretARNSillaca:
    Description: "Arn del secret manager de la base de datos AFV-Sillaca"
    Value: !Ref secretManagerDataBaseAfvSillaca
