AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API deployment

Parameters:
  ApiGatewayAPIDmFletes:
    Type: String
  StageName:
    Type: String
    Default: flete

Resources:
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGatewayAPIDmFletes
      Description: api deployment
      StageName: !Ref StageName

Outputs:
  StageAPIDmFletes:
    Value: !Ref StageName
