AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack sns msart

Parameters:
  BusPeticionesSflAfvSNSTopicArn:
    Type: String
  ArticulosSQSArn:
    Type: String

Resources:
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref BusPeticionesSflAfvSNSTopicArn
      FilterPolicy: { "ID_MICROSERVICIO": [{ "numeric": ["=", 1] }] }
      Endpoint: !Ref ArticulosSQSArn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Ref AWS::Region
