AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API

Resources:
  ApiGatewayAPIColaboradores:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: mave-mscolab-api-colaboradores
      Description: API - Microservicio Colaboradores
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiResourcesTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources.yml
      Parameters:
        ApiGatewayAPIColaboradores: !Ref ApiGatewayAPIColaboradores
        ApiGatewayRestApiRoot: !GetAtt ApiGatewayAPIColaboradores.RootResourceId
    DependsOn:
      - ApiGatewayAPIColaboradores

  ApiDeploymentTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./deployment.yml
      Parameters:
        ApiGatewayAPIColaboradores: !Ref ApiGatewayAPIColaboradores
    DependsOn:
      - ApiResourcesTemplate

Outputs:
  ApiGatewayAPIColaboradores:
    Description: API ID
    Value: !Ref ApiGatewayAPIColaboradores
