AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API resources regla_descuento_detalle

Parameters:
  ApiGatewayAPIDmDistGeo:
    Type: String
  ApiGatewayRestApiRoot:
    Type: String

Resources:
  ApiGatewayResource3:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayAPIDmDistGeo
      PathPart: country
      ParentId: !Ref ApiGatewayRestApiRoot

  ApiGatewayMethod3:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIDmDistGeo
      ResourceId: !Ref ApiGatewayResource3
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref ApiGatewayResource3
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-msdgeo-lbda-cyc_pais/invocations
