AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack sns mstcam

Parameters:
  TasaCambioSQSArn:
    Type: String
  BusPeticionesSflAfvSNSTopicArn:
    Type: String

Resources:
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref BusPeticionesSflAfvSNSTopicArn
      FilterPolicy: { "ID_MICROSERVICIO": [{ "numeric": ["=", 12] }] }
      Endpoint: !Ref TasaCambioSQSArn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Ref AWS::Region
