AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API

Resources:
  ApiGatewayAPICliente:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: mave-mscli-api-clientes
      Description: API - Microservicio Cliente
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiResourcesTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources.yml
      Parameters:
        ApiGatewayAPICliente: !Ref ApiGatewayAPICliente
        ApiGatewayRestApiRoot: !GetAtt ApiGatewayAPICliente.RootResourceId
    DependsOn:
      - ApiGatewayAPICliente

  ApiDeploymentTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./deployment.yml
      Parameters:
        ApiGatewayAPICliente: !Ref ApiGatewayAPICliente
    DependsOn:
      - ApiResourcesTemplate

Outputs:
  ApiGatewayAPICliente:
    Description: API ID
    Value: !Ref ApiGatewayAPICliente
