AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API resources anexos

Parameters:
  ApiGatewayAPIMigrationAfvSfl:
    Type: String
  ResourceV1:
    Type: String

Resources:
  #TODO add api resources
  # FletesResource:
  #   Type: AWS::ApiGateway::Resource
  #   Properties:
  #     RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
  #     PathPart: fletes
  #     ParentId: !Ref ResourceV1

  # FletesPostMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
  #     ResourceId: !Ref FletesResource
  #     HttpMethod: POST
  #     AuthorizationType: NONE
  #     ApiKeyRequired: false
  #     RequestParameters: {}
  #     MethodResponses:
  #       - ResponseModels:
  #           "application/json": "Empty"
  #         StatusCode: "200"
  #     Integration:
  #       CacheNamespace: !Ref FletesResource
  #       ContentHandling: CONVERT_TO_TEXT
  #       IntegrationHttpMethod: POST
  #       IntegrationResponses:
  #         - ResponseTemplates: {}
  #           StatusCode: "200"
  #       PassthroughBehavior: WHEN_NO_MATCH
  #       TimeoutInMillis: 29000
  #       Type: AWS_PROXY
  #       Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"
