AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API deployment

Parameters:
  ApiGatewayAPIMigrationAfvSfl:
    Type: String

Resources:
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      Description: deployment API-AFV-SFL
      StageName: MaVE-int-SFL-AFV
