AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API resources clientes

Parameters:
  ApiGatewayAPIMigrationAfvSfl:
    Type: String
  ResourceV1:
    Type: String

Resources:
  # Resource /clientes
  ClientesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      PathPart: clientes
      ParentId: !Ref ResourceV1

  ClientesPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      ResourceId: !Ref ClientesResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref ClientesResource
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"

  ClientesPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      ResourceId: !Ref ClientesResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref ClientesResource
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"

  ClientesDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      ResourceId: !Ref ClientesResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref ClientesResource
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"

  # Resource /clientes/conceptoTributario
  ConceptoTributarioResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      PathPart: conceptoTributario
      ParentId: !Ref ClientesResource

  ConceptoTributarioPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      ResourceId: !Ref ConceptoTributarioResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref ConceptoTributarioResource
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"

  # Resource /clientes/direcciones
  DireccionesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      PathPart: direcciones
      ParentId: !Ref ClientesResource

  DireccionesPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      ResourceId: !Ref DireccionesResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref DireccionesResource
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"

  # Resource /clientes/limiteCredito
  LimiteCreditoResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      PathPart: limiteCredito
      ParentId: !Ref ClientesResource

  LimiteCreditoPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      ResourceId: !Ref LimiteCreditoResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref LimiteCreditoResource
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"

  # Resource /clientes/representantes
  RepresentantesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      PathPart: representantes
      ParentId: !Ref ClientesResource

  RepresentantesPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      ResourceId: !Ref RepresentantesResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref RepresentantesResource
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"

  # Resource /clientes/telefonos
  TelefonosResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      PathPart: telefonos
      ParentId: !Ref ClientesResource

  TelefonosPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayAPIMigrationAfvSfl
      ResourceId: !Ref TelefonosResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: false
      RequestParameters: {}
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: "200"
      Integration:
        CacheNamespace: !Ref TelefonosResource
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mave-busSLF-lbda/invocations"
