AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack Lambda permission and triggers msimp

Parameters:
  DMImpuestoregionLambdaArn:
    Type: String
  DMTaxruleLambdaArn: 
    Type: String
  PullSQSImpLambdaArn: 
    Type: String
  ETLAddImpLambdaArn: 
    Type: String
  ETLUpdateImpLambdaArn: 
    Type: String
  ApiGatewayAPIImpuesto:
    Type: String
  ImpuestosSQSArn:
    Type: String
  PullSQSAddEventArn:
    Type: String
  PullSQSUpdateEventArn:
    Type: String

Resources:
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref DMImpuestoregionLambdaArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIImpuesto}/*/POST/region-tax"

  LambdaPermission2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref DMTaxruleLambdaArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIImpuesto}/*/POST/tax-rule"

  LambdaPermission3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ETLAddImpLambdaArn
      Principal: events.amazonaws.com
      SourceArn: !Ref PullSQSAddEventArn

  LambdaPermission4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ETLUpdateImpLambdaArn
      Principal: events.amazonaws.com
      SourceArn: !Ref PullSQSUpdateEventArn

  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Ref ImpuestosSQSArn
      FunctionName: !Ref PullSQSImpLambdaArn
      MaximumBatchingWindowInSeconds: 0
