AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack sns msimp

Parameters:
  BusPeticionesSflAfvSNSTopicArn:
    Type: String
  ImpuestosSQSArn:
    Type: String

Resources:
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref BusPeticionesSflAfvSNSTopicArn
      FilterPolicy: { "ID_MICROSERVICIO": [{"numeric":["=",10]}] }
      Endpoint: !Ref ImpuestosSQSArn
      Protocol: sqs
      RawMessageDelivery: false
      Region: !Ref AWS::Region

