SELECT
    C.IDCLIENTE AS CLIENTE,
    C.IDCATEGORIA AS CONDICION_PAGO,
    CASE
        WHEN O.STATUSORDEN = 3 THEN 'N'
        WHEN O.STATUSORDEN = 4 THEN 'A'
    END AS ESTADO,
    CONCAT(O.FECHAEMISION, 'T', O.HORAFINALIZA, '.000') AS FECHA_HORA,
    O.COMENTARIOS AS OBSERVACIONES,
    CONCAT(
        'P',
        SUBSTRING(LC.USERNAME, 2),
        SUBSTRING(Z.CODIGOZONA, 2),
        SUBSTRING(DATE_FORMAT(O.FECHAEMISION, '%Y%m%d'), 3),
        O.NUMORDEN
    ) AS PEDIDO,
    O.DESCUENTO_FLETE AS PORC_DESCUENTO1,
    RD.IDRUTAS AS RUTA,
    O.IDCOLABORADORES AS VENDEDOR,
    CONCAT(
        'P',
        SUBSTRING(LC.USERNAME, 2),
        SUBSTRING(Z.CODIGOZONA, 2),
        SUBSTRING(DATE_FORMAT(O.FECHAEMISION, '%Y%m%d'), 3),
        O.NUMORDEN_ORIGINAL
    ) AS U_Pedido_Padre,
    O.IDINSTRUMENTOPAGO AS U_Instrumento_Pago,
    I.NOMBRECORTO AS U_Descripcion,
    CASE
        WHEN O.IDORIGEN = 100 THEN 'S'
        ELSE 'N'
    END AS U_ORIGENCATALOGO
FROM
    orden_lote O
    INNER JOIN cliente C ON O.IDCLIENTE = C.IDCLIENTE
    INNER JOIN rutasdetalle RD ON O.IDCLIENTE = RD.IDCLIENTE
    INNER JOIN instrumentopago I ON O.IDINSTRUMENTOPAGO = I.IDINSTRUMENTOPAGO
    INNER JOIN zonas Z ON O.IDZONAS = Z.IDZONAS
    INNER JOIN logincolaborador LC ON LC.IDCOLABORADORES = O.IDCOLABORADORES
WHERE
    O.NUMORDEN = $ { NUMORDEN }
    AND O.IDCLIENTE = $ { IDCLIENTE }
    AND O.FECHAEMISION = ${ FECHAEMISION };