-- consulta validacion de precios de pedidos
SELECT O.IDARTICULO, O.PRECIOUNITARIO, A.PRECIOLISTA, (O.PRECIOUNITARIO- A.PRECIOLISTA) AS DIFERENCIA , O.NUMORDEN, O.IDCLIENTE,FECHATRANSMISION 
FROM DBAFV.ORDENDETALLE_LOTE O INNER JOIN DBAFV.ARTICULOS_LPV A ON O.IDARTICULO=A.IDARTICULO 
WHERE O.FECHATRANSMISION>='2023-09-07 13:30:00' AND (O.PRECIOUNITARIO- A.PRECIOLISTA)<-0.4 AND (O.PRECIOUNITARIO- A.PRECIOLISTA)<-0.4 ;