AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API deployment

Parameters:
  ApiGatewayAPIDmBan:
    Type: String
  StageName:
    Type: String
    Default: bank-accounts

Resources:
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGatewayAPIDmBan
      Description: api deployment
      StageName: !Ref StageName

Outputs:
  StageAPIDmBan:
    Value: !Ref StageName
