AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack lambdas mscolab

Globals:
  Function:
    MemorySize: 128
    Tracing: PassThrough
    Timeout: 600
    Runtime: nodejs16.x
    EphemeralStorage:
      Size: 512
    Architectures:
      - "x86_64"
    # VpcConfig:
    #   SubnetIds:
    #     - !Ref SubnetId1
    #   SecurityGroupIds:
    #     - !Ref SecurityGroupIds

Parameters:
  # LAYERS
  LayerMySQL:
    Type: String
  LayerSecretManager:
    Type: String
  LayerSendEvent:
    Type: String
  LayerAxiosGraphql:
    Type: String
  # VPC
  SecurityGroupIds:
    Type: String
  SubnetId1:
    Type: String
  # SECRETS
  SecretARNBeval:
    Type: String
  SecretARNFebeca:
    Type: String
  SecretARNSillaca:
    Type: String
  # APIS
  ApiGatewayAPIColaboradores:
    Type: String
  ApiGatewayAPIDivComercial:
    Type: String
  RoleLambdaGlobalSflAfvArn:
    Type: String

Resources:
  DMColaboradores:
    Type: AWS::Serverless::Function
    Properties:
      Description: "SFL-AFV | Microservicio Colaboradores | Procesamiento de Datos | Colaboradores"
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          SECRET_ARN_BEVAL: !Ref SecretARNBeval
          SECRET_ARN_FEBECA: !Ref SecretARNFebeca
          SECRET_ARN_SILLACA: !Ref SecretARNSillaca
          TABLE: "colaboradores"
      FunctionName: mave-mscolab-lbda-dm-colaboradores
      Handler: index.handler
      CodeUri: ../../src/lambdas/mscolab/mave-mscolab-lbda-dm-colaboradores/
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerMySQL
        - !Ref LayerSecretManager

  DMLogincolaborador:
    Type: AWS::Serverless::Function
    Properties:
      Description: "SFL-AFV | Microservicio Colaboradores | Procesamiento de Datos | Logincolaborador"
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          SECRET_ARN_BEVAL: !Ref SecretARNBeval
          SECRET_ARN_FEBECA: !Ref SecretARNFebeca
          SECRET_ARN_SILLACA: !Ref SecretARNSillaca
          TABLE: "logincolaborador"
      FunctionName: mave-mscolab-lbda-dm-logincolaborador
      Handler: index.handler
      CodeUri: ../../src/lambdas/mscolab/mave-mscolab-lbda-dm-logincolaborador/
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerMySQL
        - !Ref LayerSecretManager

  DMZonarepresentante:
    Type: AWS::Serverless::Function
    Properties:
      Description: "SFL-AFV | Microservicio Colaboradores | Procesamiento de Datos | Zonarepresentante"
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          SECRET_ARN_BEVAL: !Ref SecretARNBeval
          SECRET_ARN_FEBECA: !Ref SecretARNFebeca
          SECRET_ARN_SILLACA: !Ref SecretARNSillaca
          TABLE: "zonarepresentante"
      FunctionName: mave-mscolab-lbda-dm-zonarepresentante
      Handler: index.handler
      CodeUri: ../../src/lambdas/mscolab/mave-mscolab-lbda-dm-zonarepresentante/
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerMySQL
        - !Ref LayerSecretManager

  ETLAddColabLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: "SFL-AFV | Microservicio Colaboradores | ETL Add"
      Environment:
        Variables:
          API_URL: !Sub "https://${ApiGatewayAPIColaboradores}.execute-api.${AWS::Region}.amazonaws.com/collaborators"
          API_DCOM_URL: !Sub "https://${ApiGatewayAPIDivComercial}.execute-api.${AWS::Region}.amazonaws.com/ComercialDiv"
      FunctionName: mave-mscolab-lbda-etl-Add
      ReservedConcurrentExecutions: 1
      Handler: index.handler
      CodeUri: ../../src/lambdas/mscolab/mave-mscolab-lbda-etl-Add/
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerAxiosGraphql
        - !Ref LayerSendEvent

  ETLInactivateColabLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: "SFL-AFV | Microservicio Colaboradores | ETL Inactivate"
      Environment:
        Variables:
          API_URL: !Sub "https://${ApiGatewayAPIColaboradores}.execute-api.${AWS::Region}.amazonaws.com/collaborators"
      FunctionName: mave-mscolab-lbda-etl-Inactive
      ReservedConcurrentExecutions: 1
      Handler: index.handler
      CodeUri: ../../src/lambdas/mscolab/mave-mscolab-lbda-etl-Inactive/
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerAxiosGraphql
        - !Ref LayerSendEvent

  ETLUpdateColabLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: "SFL-AFV | Microservicio Colaboradores | ETL Update"
      Environment:
        Variables:
          API_URL: !Sub "https://${ApiGatewayAPIColaboradores}.execute-api.${AWS::Region}.amazonaws.com/collaborators"
          API_DCOM_URL: !Sub "https://${ApiGatewayAPIDivComercial}.execute-api.${AWS::Region}.amazonaws.com/ComercialDiv"
      FunctionName: mave-mscolab-lbda-etl-Update
      ReservedConcurrentExecutions: 1
      Handler: index.handler
      CodeUri: ../../src/lambdas/mscolab/mave-mscolab-lbda-etl-Update/
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerAxiosGraphql
        - !Ref LayerSendEvent

  PullSQSColabLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: "SFL-AFV | Microservicio Colaboradores | Pull de Cola SQS"
      FunctionName: mave-mscolab-lbda-pullSQS
      Handler: index.handler
      CodeUri: ../../src/lambdas/mscolab/mave-mscolab-lbda-pullSQS/
      Role: !Ref RoleLambdaGlobalSflAfvArn
      Layers:
        - !Ref LayerSendEvent

Outputs:
  DMColaboradoresArn:
    Description: DMColaboradores Arn
    Value: !GetAtt DMColaboradores.Arn
  DMLogincolaboradorArn:
    Description: DMLogincolaborador Arn
    Value: !GetAtt DMLogincolaborador.Arn
  DMZonarepresentanteArn:
    Description: DMZonarepresentante Arn
    Value: !GetAtt DMZonarepresentante.Arn
  ETLAddColabLambdaArn:
    Description: ETLAddColabLambda Arn
    Value: !GetAtt ETLAddColabLambda.Arn
  ETLInactivateColabLambdaArn:
    Description: ETLInactivateColabLambda Arn
    Value: !GetAtt ETLInactivateColabLambda.Arn
  ETLUpdateColabLambdaArn:
    Description: ETLUpdateColabLambda Arn
    Value: !GetAtt ETLUpdateColabLambda.Arn
  PullSQSColabLambdaArn:
    Description: PullSQSColabLambda Arn
    Value: !GetAtt PullSQSColabLambda.Arn
