AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack Lambda permission and triggers mscolab

Parameters:
  DMColaboradoresArn:
    Type: String
  DMLogincolaboradorArn:
    Type: String
  DMZonarepresentanteArn:
    Type: String
  ETLAddColabLambdaArn:
    Type: String
  ETLInactivateColabLambdaArn:
    Type: String
  ETLUpdateColabLambdaArn:
    Type: String
  ColaboradoresSQSArn:
    Type: String
  PullSQSColabLambdaArn:
    Type: String
  ApiGatewayAPIColaboradores:
    Type: String
  PullSQSAddEventArn:
    Type: String
  PullSQSInactivateEventArn:
    Type: String
  PullSQSUpdateEventArn:
    Type: String

Resources:
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref DMColaboradoresArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIColaboradores}/*/POST/collaborators"

  LambdaPermission1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref DMLogincolaboradorArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIColaboradores}/*/POST/login-collaborator"

  LambdaPermission2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref DMZonarepresentanteArn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIColaboradores}/*/POST/representative-zone"

  LambdaPermission3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ETLAddColabLambdaArn
      Principal: events.amazonaws.com
      SourceArn: !Ref PullSQSAddEventArn

  LambdaPermission4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ETLInactivateColabLambdaArn
      Principal: events.amazonaws.com
      SourceArn: !Ref PullSQSInactivateEventArn

  LambdaPermission5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ETLUpdateColabLambdaArn
      Principal: events.amazonaws.com
      SourceArn: !Ref PullSQSUpdateEventArn

  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Ref ColaboradoresSQSArn
      FunctionName: !Ref PullSQSColabLambdaArn
      MaximumBatchingWindowInSeconds: 0
