AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack mscolab

Parameters:
  #LAYERS
  LayerMySQL:
    Type: String
  LayerSecretManager:
    Type: String
  LayerSendEvent:
    Type: String
  LayerAxiosGraphql:
    Type: String
  # VPC
  SecurityGroupIds:
    Type: String
  SubnetId1:
    Type: String
  # SECRETS
  SecretARNBeval:
    Type: String
  SecretARNFebeca:
    Type: String
  SecretARNSillaca:
    Type: String
  # API
  ApiGatewayAPIDivComercial:
    Type: String
  # Adds
  BusPeticionesSflAfvSNSTopicArn:
    Type: String
  RoleLambdaGlobalSflAfvArn:
    Type: String

Resources:
  ApiGatewayTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/template.yml

  EventRulesTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./events.yml
      Parameters:
        ETLAddCompletedLogArn: !GetAtt LogsTemplate.Outputs.ETLAddCompletedLogArn
        ETLAddFailedLogArn: !GetAtt LogsTemplate.Outputs.ETLAddFailedLogArn
        ETLInactivateCompletedLogArn: !GetAtt LogsTemplate.Outputs.ETLInactivateCompletedLogArn
        ETLInactivateFailedLogArn: !GetAtt LogsTemplate.Outputs.ETLInactivateFailedLogArn
        ETLUpdateCompletedLogArn: !GetAtt LogsTemplate.Outputs.ETLUpdateCompletedLogArn
        ETLUpdateFailedLogArn: !GetAtt LogsTemplate.Outputs.ETLUpdateFailedLogArn
        ETLAddColabLambdaArn: !GetAtt LambdasTemplate.Outputs.ETLAddColabLambdaArn
        ETLInactivateColabLambdaArn: !GetAtt LambdasTemplate.Outputs.ETLInactivateColabLambdaArn
        ETLUpdateColabLambdaArn: !GetAtt LambdasTemplate.Outputs.ETLUpdateColabLambdaArn
    DependsOn:
      - LambdasTemplate
      - LogsTemplate

  LambdasTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambdas.yml
      Parameters:
        LayerMySQL: !Ref LayerMySQL
        LayerSecretManager: !Ref LayerSecretManager
        LayerSendEvent: !Ref LayerSendEvent
        LayerAxiosGraphql: !Ref LayerAxiosGraphql
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetId1: !Ref SubnetId1
        SecretARNBeval: !Ref SecretARNBeval
        SecretARNFebeca: !Ref SecretARNFebeca
        SecretARNSillaca: !Ref SecretARNSillaca
        ApiGatewayAPIColaboradores: !GetAtt ApiGatewayTemplate.Outputs.ApiGatewayAPIColaboradores
        ApiGatewayAPIDivComercial: !Ref ApiGatewayAPIDivComercial
        RoleLambdaGlobalSflAfvArn: !Ref RoleLambdaGlobalSflAfvArn
    DependsOn:
      - ApiGatewayTemplate

  LambdaPermissionsTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambdaTriggers.yml
      Parameters:
        DMColaboradoresArn: !GetAtt LambdasTemplate.Outputs.DMColaboradoresArn
        DMLogincolaboradorArn: !GetAtt LambdasTemplate.Outputs.DMLogincolaboradorArn
        DMZonarepresentanteArn: !GetAtt LambdasTemplate.Outputs.DMZonarepresentanteArn
        ETLAddColabLambdaArn: !GetAtt LambdasTemplate.Outputs.ETLAddColabLambdaArn
        ETLInactivateColabLambdaArn: !GetAtt LambdasTemplate.Outputs.ETLInactivateColabLambdaArn
        ETLUpdateColabLambdaArn: !GetAtt LambdasTemplate.Outputs.ETLUpdateColabLambdaArn
        PullSQSColabLambdaArn: !GetAtt LambdasTemplate.Outputs.PullSQSColabLambdaArn
        ApiGatewayAPIColaboradores: !GetAtt ApiGatewayTemplate.Outputs.ApiGatewayAPIColaboradores
        ColaboradoresSQSArn: !GetAtt SQSTemplate.Outputs.ColaboradoresSQSArn
        PullSQSAddEventArn: !GetAtt EventRulesTemplate.Outputs.PullSQSAddEventArn
        PullSQSInactivateEventArn: !GetAtt EventRulesTemplate.Outputs.PullSQSInactivateEventArn
        PullSQSUpdateEventArn: !GetAtt EventRulesTemplate.Outputs.PullSQSUpdateEventArn
    DependsOn:
      - EventRulesTemplate
      - SQSTemplate

  LogsTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./logs.yml

  SQSTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./sqs.yml
      Parameters:
        BusPeticionesSflAfvSNSTopicArn: !Ref BusPeticionesSflAfvSNSTopicArn

  SNSTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./sns.yml
      Parameters:
        ColaboradoresSQSArn: !GetAtt SQSTemplate.Outputs.ColaboradoresSQSArn
        BusPeticionesSflAfvSNSTopicArn: !Ref BusPeticionesSflAfvSNSTopicArn
    DependsOn:
      - SQSTemplate

Outputs:
  ApiGatewayAPIColaboradores:
    Value: !GetAtt ApiGatewayTemplate.Outputs.ApiGatewayAPIColaboradores
