AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack Lambda permission and triggers API-SFL-AFV

Parameters:
  BusSflLambdaArn:
    Type: String
  BusDocComercialesLambdaArn:
    Type: String
  BusExistenciaLambdaArn:
    Type: String
  ApiGatewayAPIMigrationAfvSfl:
    Type: String

Resources:
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BusSflLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIMigrationAfvSfl}/*

  LambdaBusDocComercialesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BusDocComercialesLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIMigrationAfvSfl}/*

  LambdaBusExistenciaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BusExistenciaLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayAPIMigrationAfvSfl}/*
