AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stack API-SFL-AFV

Parameters:
  LayerSendSNSSQS:
    Type: String

  SecurityGroupIds:
    Type: String
  SubnetId1:
    Type: String

  RoleLambdaGlobalSflAfvArn:
    Type: String

Resources:
  ApiTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/template.yml

  SNSTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./sns.yml

  LambdasTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambdas.yml
      Parameters:
        RoleLambdaGlobalSflAfvArn: !Ref RoleLambdaGlobalSflAfvArn
        LayerSendSNSSQS: !Ref LayerSendSNSSQS

        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetId1: !Ref SubnetId1

        BusPeticionesSflAfvSNSTopicArn: !GetAtt SNSTemplate.Outputs.BusPeticionesSflAfvSNSTopicArn
    DependsOn:
      - SNSTemplate

  LambdaPermissionsTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambdaTriggers.yml
      Parameters:
        BusSflLambdaArn: !GetAtt LambdasTemplate.Outputs.BusSflLambdaArn
        BusDocComercialesLambdaArn: !GetAtt LambdasTemplate.Outputs.BusDocComercialesLambdaArn
        BusExistenciaLambdaArn: !GetAtt LambdasTemplate.Outputs.BusExistenciaLambdaArn

        ApiGatewayAPIMigrationAfvSfl: !GetAtt ApiTemplate.Outputs.ApiGatewayAPIMigrationAfvSfl

    DependsOn:
      - ApiTemplate
      - LambdasTemplate

Outputs:
  BusPeticionesSflAfvSNSTopicArn:
    Value: !GetAtt SNSTemplate.Outputs.BusPeticionesSflAfvSNSTopicArn
